services:
  - type: web
    plan: free
    name: asistentes
    repo: https://github.com/davidalencia/mapa_asistentes
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python -m gunicorn map:server -b:8000"
